###
### Server config: IP-Address and port to listen to.
###

server:
    ip: 192.168.42.53
    port: 8081


###
### CA config: Passphrase for CA Key
###

ca:
    passphrase: yyyy


###
### OCSP server config:
### IP-Address and port to listen to,
### Passphrase used to encrypt the OCSP signign key.
###

ocsp:
    ip: 192.168.42.53
    port: 2560
    passphrase: yyyy
