###
### Server config: IP-Address and port to listen to.
###

server:
    ip: 0.0.0.0
    api:
        port: 8081
        ext_url: ca.adito.local
    public:
        port: 8080
        ext_url: ca.adito.local
    ocsp:
        port: 2560
        ext_url: ca.adito.local


###
### CA config: Passphrase for CA Key
###

ca:
    root:
        passphrase: yyyy
        days: 3650
        country: DE
        state: Bayern
        locality: Geisenhausen
        organization: ADITO Software GmbH
        commonname: Root CA
    intermediate:
        passphrase: yyyy
        days: 3650
        country: DE
        state: Bayern
        locality: Geisenhausen
        organization: ADITO Software GmbH
        commonname: Intermediate CA
        ocsp:
            passphrase: yyyy
            country: DE


###
### Settings for end user certificates
###
cert:
    lifetime_default: 1
    lifetime_max: 365
