###
### Server config: IP-Address and port to listen to.
###

server:
    ip: 0.0.0.0
    port: 8081


###
### CA config: Passphrase for CA Key
###

ca:
    root:
        passphrase: yyyy
        days: 3650
        country: DE
        state: Bayern
        locality: Geisenhausen
        organization: ADITO Software GmbH
        commonname: Root CA
    intermediate:
        passphrase: yyyy
        days: 3650
        country: DE
        state: Bayern
        locality: Geisenhausen
        organization: ADITO Software GmbH
        commonname: Intermediate CA
        ocsp:
            passphrase: yyyy
            country: DE
            commonname: ocsp.adito.local:2560
        crl:
            url: http://crl.adito.local:2561/crl.pem


###
### OCSP server config:
### IP-Address and port to listen to,
### Passphrase used to encrypt the OCSP signing key.
### Password and URL are used to generate PKI. If you want to change these settings, you have to re-create your pki!
###

ocsp:
    ip: 0.0.0.0
    port: 2560


###
### CRL HTTP server config
### baseurl used to generate PKI. If you want to change these settings, you have to re-create your pki!
###

crl:
    ip: 0.0.0.0
    port: 2561
